(() => {
  const template = document.createElement('template');
  template.innerHTML = '<aside class="sidebar" id="sidebar">\n      <a class="brand" href="index.html" aria-label="Accueil">\n        <span class="brand-mark"><img src="images/logo_v7_trans.png" alt="" width="44" height="44"></span>\n        <span><strong>L\'Atelier Médieval</strong><small>Modélisme & figurines</small></span>\n      </a>\n      <nav class="nav-main" aria-label="Navigation principale">\n        <a class="nav-link" href="index.html"><span>⌂</span>Accueil</a>\n        <a class="nav-link" href="projets.html"><span>◇</span>Projets et œuvres</a>\n        <a class="nav-link" href="instructions.html"><span>✦</span>Tutoriels</a>\n        <a class="nav-link" href="about.html"><span>◎</span>À propos</a>\n      </nav>\n      <div class="sidebar-section">\n        <p>Explorer</p>\n        <a class="category-link" href="projets.html?categorie=Maquettes médiévales">Maquettes médiévales</a>\n        <a class="category-link" href="projets.html?categorie=Maquettes Antiquité">Maquettes Antiquité</a>\n        <a class="category-link" href="projets.html?categorie=Figurines médiévales">Figurines médiévales</a>\n        <a class="category-link" href="projets.html?categorie=Figurines Antiquité">Figurines Antiquité</a>\n        <a class="category-link" href="projets.html?categorie=Décors de crèche">Décors de crèche</a>\n        <a class="category-link" href="projets.html?categorie=Santons">Figurines santons</a>\n        <a class="category-link" href="projets.html?categorie=Autres">Autres</a>\n      </div>\n      <div class="sidebar-footer">\n        <span class="status-dot"></span> L\'Atelier Médiéval\n      </div>\n    </aside>';
  const element = template.content.firstElementChild;
  const activePage = { home: 'index.html', projects: 'projets.html', 'project-detail': 'projets.html', tutorials: 'instructions.html', 'tutorial-detail': 'instructions.html', about: 'about.html' }[document.body.dataset.page];
  const activeLink = [...element.querySelectorAll('.nav-main a')].find(link => link.getAttribute('href') === activePage);
  if (activeLink) { activeLink.classList.add('active'); activeLink.setAttribute('aria-current', 'page'); }
  document.currentScript.replaceWith(element);
})();
